####
##
## Derived from 
## GitHub: https://github.com/konnected-io/konnected-esphome
## https://install.konnected.io/esphome
####

####
## Pinouts
## https://help.konnected.io/support/solutions/articles/32000028978-inputs-and-outputs
####

####
# GENERAL SETTINGS
# Customize these variables to your preferences and needs
# more: https://esphome.io/guides/configuration-types.html#substitutions
substitutions:

  ####
  # NAME
  name: alarm-panel-pro-0e05d0
  friendly_name: Alarm Panel Pro
  project_name:  fearandloathinginithell.alarm-panel-pro-esp32
  device_description: "Konnected pro ESPHome"
  project_version: "0.1.0"

  # Webserver credentials ⬇ #
  web_username: !secret alarm-panel-pro-0e05d0_web_username
  web_password: !secret alarm-panel-pro-0e05d0_web_password

  # Update credentials ⬇ #
  ota_password: !secret alarm-panel-pro-0e05d0_ota_password

  # API credentials ⬇ #
  api_encryption_key: !secret alarm-panel-pro-0e05d0_api_encryption_key
  
  # ETHERNET CONFIG
  ethernet_type: LAN8720 # Alarm Panel Pro up to 1.7

  sensor_debounce_time: 200ms
  warning_beep_pulse_time: 100ms
  warning_beep_pause_time: 130ms
  warning_beep_internal_only: "false"

  ####
  # ZONE MAPPING
  # Do not edit this section.
  zone1: GPIO4
  zone2: GPIO2
  zone3: GPIO15
  zone4: GPIO13
  zone5: GPIO18
  zone6: GPIO14
  zone7: GPIO33
  zone8: GPIO32
  zone9: GPIO36
  zone10: GPIO39
  zone11: GPIO34
  zone12: GPIO35
  alarm1: GPIO12
  alarm2: GPIO5
  out1: GPIO23
  out2: GPIO5
  status_led: GPIO3
  
  ####
  # CONNECTION MAPPINGS
  warning_beep_pin: $zone3



####
# INPUT ZONE COMMON SETTINGS
.input_zone_common: &input_zone_common
  platform: gpio   
  filters:
    - delayed_on_off: $sensor_debounce_time
  on_state:
    then:
      - light.turn_on: blue_status_led
      - delay: 100ms
      - light.turn_off: blue_status_led

# DS18B20 digital thermometer
dallas:
  pin: $zone1

####
# BINARY SENSOR SETUP
# A "Binary Sensor" is any type of sensor that has two states, such as open/closed or detected/not-detected.
# Set up zones for door, window, motion, smoke/fire, CO, water/leak sensors in this section by repeating the configuration
# block below for each zone.
binary_sensor:

  - id: zone8
    name: !secret alarm-panel-pro-0e05d0_zone8_name
    device_class: !secret alarm-panel-pro-0e05d0_zone8_class
    pin:
      number: $zone8
      mode: INPUT_PULLUP
    <<: *input_zone_common

  - id: zone9
    name: !secret alarm-panel-pro-0e05d0_zone9_name
    device_class: !secret alarm-panel-pro-0e05d0_zone9_class
    pin:
      number: $zone9
      mode: INPUT
    <<: *input_zone_common

  - id: zone10
    name: !secret alarm-panel-pro-0e05d0_zone10_name
    device_class: !secret alarm-panel-pro-0e05d0_zone10_class
    pin:
      number: $zone10
      mode: INPUT
    <<: *input_zone_common

  - id: zone11
    name: !secret alarm-panel-pro-0e05d0_zone11_name
    device_class: !secret alarm-panel-pro-0e05d0_zone11_class
    platform: gpio    
    pin:
      number: $zone11
      mode: INPUT
    <<: *input_zone_common


button:
  - platform: restart
    name: "Restart - $name"

# sensor:
#  - platform: dallas
#    index: 0
#    name: "test"

switch:   
  - id: alarm1
    name: Internal Siren
    pin: $alarm1
    platform: gpio
    icon: mdi:bullhorn

  - id: alarm2
    name: External Siren
    pin: $alarm2
    platform: gpio
    icon: mdi:bullhorn


####
# PACKAGES
# Each package includes the alarm panel feature
packages:

  ####
  # CORE
  # This package is required and sets up core features.
  core: github://fearandloathinginithell/alarm-panel-pro-esp32/packages/core-esp32.yaml@master

  ####
  # ETHERNET
  # Enables ethernet connectivity. Uncomment below to enable ethernet.
  ethernet: github://fearandloathinginithell/alarm-panel-pro-esp32/packages/ethernet.yaml@master

  ####
  # WARNING BEEP
  # Enables a 'Warning Beep' entity, intended to be used with a piezo buzzer. This is 
  # implemented using a light entity with strobe effect to create a repeated beeping sound.
  warning_beep: github://fearandloathinginithell/alarm-panel-pro-esp32/packages/warning-beep.yaml@master

  ####
  # STATUS LED
  # Enables the onboard blue status LED as an activity/error indicator
  status_led: github://fearandloathinginithell/alarm-panel-pro-esp32/packages/status-led.yaml@master
  
  
dashboard_import:
  package_import_url: github://fearandloathinginithell/alarm-panel-pro-esp32/alarm-panel-pro-esp32.yaml@master
  import_full_config: true

####
# WEB SEVER
web_server:
  include_internal: true
  port: 80
  auth:
    username: '${web_username}'
    password: '${web_password}'

#### 
# LOGGER
# more: https://esphome.io/components/logger.html
logger:

####
# NATIVE API for HOME ASSISTANT
# more: https://esphome.io/components/api.html
api:
  encryption:
    key: '${api_encryption_key}'

#### 
# OTA UPDATES
# more: https://esphome.io/components/ota.html
ota:
  password: '${ota_password}'
